"""Add roles

Revision ID: f27fbe36cf77
Revises: 5db0ea5478d5
Create Date: 2024-10-28 14:11:53.399388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = 'f27fbe36cf77'
down_revision: Union[str, None] = '5db0ea5478d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

roles_enum = ENUM('admin', 'user', name='roles', create_type=True)

def upgrade() -> None:
    roles_enum.create(op.get_bind())
    op.add_column('users', sa.Column('roles', roles_enum, nullable=False, server_default='user'))
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'roles')
    # Удаляем тип Enum
    roles_enum.drop(op.get_bind())
    # ### end Alembic commands ###
